<?php

namespace App\Filament\Pharmacy\Resources\PharmacyProducts\Pages;

use App\Filament\Pharmacy\Resources\PharmacyProducts\PharmacyProductResource;
use Filament\Facades\Filament;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Filament\Schemas\Schema;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;
use Src\Medication\Domain\Models\Medication;
use Src\Medication\Domain\Models\MedicationVariant;
use Src\Shared\Domain\Models\User;

class CreatePharmacyProduct extends CreateRecord
{
    protected static string $resource = PharmacyProductResource::class;

    public function form(Schema $form): Schema
    {
        return $form
            ->schema([
                Select::make('medication_variant_id')
                    ->label('Select Medication')
                    ->searchable()
                    ->preload()
                    ->getSearchResultsUsing(fn (string $search) => MedicationVariant::query()
                        ->whereHas('medication', fn (Builder $query) => $query->where('name', 'like', "%{$search}%")->orWhere('generic_name', 'like', "%{$search}%"))
                        ->whereHas('medication', fn (Builder $query) => $query->where('status', 'approved'))
                        ->limit(50)
                        ->get()
                        ->mapWithKeys(fn (MedicationVariant $variant) => [$variant->id => $variant->medication->name.' ('.$variant->name.')'])
                    )
                    ->getOptionLabelUsing(fn ($value): ?string => MedicationVariant::find($value)?->medication->name.' ('.MedicationVariant::find($value)?->name.')')
                    ->required()
                    ->createOptionForm([
                        // Form to create a new MEDICATION (status will be pending)
                        TextInput::make('name')->required()->label('Medication Name (e.g., Paracetamol)'),
                        TextInput::make('generic_name'),
                        Textarea::make('description'),
                        FileUpload::make('image')->image()->disk('public')->directory('medication-images'),
                        Toggle::make('is_prescription')->label('Requires Prescription'),
                    ])
                    ->createOptionUsing(function (array $data): int {
                        // This logic runs when a pharmacist creates a new medication
                        $medication = Medication::create([
                            ...$data,
                            'status' => 'pending_review',
                            'created_by_user_id' => Auth::id(),
                        ]);

                        // We create a default "General" variant for it
                        $variant = $medication->variants()->create(['name' => 'General']);

                        // Notify Admins
                        $admins = User::where('is_admin', true)->get();
                        Notification::make()
                            ->title('New Medication Submitted for Review')
                            ->body("{$medication->name} was submitted by a pharmacist.")
                            ->sendToDatabase($admins);

                        return $variant->id;
                    }),
                TextInput::make('price')->required()->numeric()->prefix('₦'),
                TextInput::make('stock')->required()->numeric()->integer(),
                TextInput::make('nafdac_number')->label('NAFDAC Number'),
            ]);
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $user = Filament::auth()->user();
        $data['user_id'] = $user->id;
        $data['pharmacy_id'] = $user->pharmacy_id;

        // The slug will be generated by an observer for uniqueness per pharmacy.
        return $data;
    }
}
